[package]
name = "gfs-lite"
version = "0.1.0"
edition = "2021"

[dependencies]
tarpc = { version = "0.35", features = ["full"] }
tokio = { version = "1", features = ["full"] }
futures = "0.3"
rand = "0.8.5"

[dev-dependencies]
proptest = "1.5"
